app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from flask_login import UserMixin

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    password_hash = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    posts = db.relationship('Post', backref='user', lazy="dynamic")
    Comments = db.relationship('Comment', backref='user', lazy="dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.username}'


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), index=True)
    body = db.Column(db.String(255), index=True)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref='post')

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_posts(cls, id):
        posts = Post.query.filter_by(user_id=id).all()
        return posts

    def __repr__(self):
        return '<Post {}>'.format(self.body)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment_post = db.Column(db.String(255), index=True)
    time = db.Column(db.DateTime, default=datetime.utcnow)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def save_comments(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, id):
        comments = Comment.query.filter_by(post_id=id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class BlogForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    post = TextAreaField('Blog', validators=[DataRequired()])
    submit = SubmitField('Submit')


class CommentsForm(FlaskForm):
    comment = TextAreaField('Comments', validators=[DataRequired()])
    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about yourself.', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet, configure_uploads, IMAGES


db = SQLAlchemy()
bootstrap = Bootstrap()
mail = Mail()


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos', IMAGES)


def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    # Initializing flask extensions

    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # setting config
    from .requests import configure_request
    configure_request(app)

    # configure UploadSet
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from .import views,forms

app/main/views.py
from . import main
from flask import render_template, redirect, url_for, request, abort, flash
from ..requests import get_random_quote
from ..models import User, Post, Comment
from flask_login import login_required, current_user
from .. import db, photos
from .forms import BlogForm, CommentsForm, UpdateProfile


@main.route('/')
def index():
    quote = get_random_quote()

    return render_template('index.html', quote=quote)


@main.route('/blogs')
def blogs():
    posts = Post.query.order_by(Post.timestamp.desc()).all()

    return render_template('blogs.html', posts=posts)


@main.route('/blogs/new/', methods=["GET", "POST"])
@login_required
def new_blog():
    '''
    view function that returns the blog form
    '''
    form = BlogForm()

    if form.validate_on_submit():
        post = form.post.data
        title = form.title.data

        new_post = Post(title=title, body=post, user=current_user)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('.blogs'))

    title = 'blogs'
    return render_template('new_blog.html', title=title, blog_form=form)


@main.route('/comments/new/<int:id>', methods=["GET", "POST"])
@login_required
def comment(id):
    '''
    view function that returns a form to insert a comment on a post
    '''

    form = CommentsForm()
    post = Post.query.filter_by(id=id).first()

    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(post_id=post.id, comment_post=comment, user=current_user)
        new_comment.save_comments()

        return redirect(url_for('main.comments', id=post.id))

    return render_template('new_comment.html', comment_form=form, post=post)


@main.route('/comments/<int:id>')
def comments(id):
    post = Post.query.get(id)
    comment = Comment.get_comments(post.id)
    return render_template('comments.html', comment=comment, post=post)
    print(comments)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)


@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)


@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))


@main.route("/post/<int:post_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get(post_id)
    if post.user != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted!', 'success')
    return redirect(url_for('main.blogs'))

app/templates/base.html
{% extends 'bootstrap/base.html'%}


<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block styles %}

    {{super()}}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">

{% endblock %}

app/templates/blogs.html
{% extends 'base.html' %}
{% from 'macros.html' import displayBlog with context %}

{% block content %}

<div class="container">
    <div class="row">
        {% if posts %}

        {{ displayBlog(posts)}}

        {% else %}

        <div class="card" style="width: 100%;">
            <h4 class="text-center">No posts yet click on add to add.</h4>
        </div>

        {%  endif %}

    </div>

</div>

{% endblock  %}

app/templates/comments.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
    <div class="legend">

        <h3 class="text-center">Comment Logs</h3>
        <hr>
        {% if comment %}
        <div class="row">
            {{ macro.displayComments(comment) }}
        </div>
        {% else %}
        <h3>No comments yet</h3>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}


{% block content %}
<div class="container-fluid" id="one">
    <h4 class="animated bounceInUp text-center">BLOG POST,<br>This most beautiful system of the sun, planets and comets, could only proceed from the counsel and dominion of an intelligent and powerful Being.</h4>
</div>
<br>
<div class="continer">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-4">
            </di<div class="card" style="width: 18rem;">
            <img class="card-img-top" src="https://www.rescue-uk.org/sites/default/files/styles/window_width_breakpoints_theme_rescue_large_2x/public/article/1476/teaser/c63ms_4woaazass.jpg?itok=ivfu81Qn&timestamp=1500911805" alt="Card image cap">
            <div class="card-body">
                <figcaption>
                    <h5 class="card-title fa-quote-right">-Albert Einstein</h5>
                </figcaption>
                <p class="card-text blockquote">Everybody is a genius,But if you judge a fish by its ability to climb a
                    tree it will leave all it's life believing it is stupid</p>
                <a href="" class="btn btn-sm btn btn-outline-info">more</a>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4">
            </di<div class="card" style="width: 18rem;">
            <img class="card-img-top" src="https://i.ytimg.com/vi/ZrBQmIDdls4/maxresdefault.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{quote.author}}</h5>
                <small><h6><b>Random quotes</b></h6></small>
                <p class="card-text">{{quote.quote}}</p>
                <a href="{{quote.permalink}}" class="btn btn-sm btn-outline-info">more info</a>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4">
            </di<div class="card" style="width: 18rem;">
            <img class="card-img-top" src="https://www.battlefields.org/sites/default/files/styles/facebook/public/thumbnails/image/Abraham%20Lincoln%20CIC%20Square.jpg?itok=Od9XGRzG" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Abraham Lincolin</h5>
                <p class="card-text">“Let not him who is houseless pull down the house of another, but let him work diligently and build one for himself, thus by example assuring that his own shall be safe from violence when built.”

                        .</p>
                <a href='http://www.quoteambition.com/famous-abraham-lincoln-quotes/' class="btn btn-outline-info btn-sm">more info</a>
            </div>
        </div>
    </div>
</div>
<hr>

{% endblock %}

app/templates/macros.html
{% macro displayBlog(my_blogs,user) %}
{% for blog in my_blogs %}

<div class="col-md-1"></div>
<div class="col-md-10">
    <div class="card m-3">
        <div class="card-header">
            <h4>{{blog.title}}</h4>
            <span><small> posted {{ mail(blog.timestamp).fromNow(refresh=True)}} </small></span>
        </div>
        <div class="card-body">
            {{blog.body}}
        </div>
        <div class="card-footer">

            <div class="row">
                <div class="col-md-2">
                    <a class="btn btn-sm btn-outline-info" href="/comments/{{blog.id}}">View Comments</a>
                </div>
                <div class="col-md-8"></div>
                <div class="col-md-2">
                    <a class="btn btn-sm btn-outline-danger m-1"
                        href="{{url_for('main.delete_post' , post_id=blog.id)}}">Delete</a>
                    <a class="btn btn-sm btn-outline-info" href="/comments/new/{{blog.id}}">Comment</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-md-1"></div>
{% endfor %}
{% endmacro %}

{% macro displayComments(comment_list) %}
{% for comment in comment_list %}

<div class="col-md-6 mb-3">
    <div class="card">
        <div class="card-body">
            <h3>{{comment.comment_post}}</h3>
        </div>
        <div class="card-footer">
            <footer class="blockquote-footer">{{comment.user.username}} commented on your pitch</footer>

        </div>
    </div>
</div>



{% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-info" style="position: sticky; top: 0; z-index: 3;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{url_for('main.blogs')}}">Blogs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{url_for('main.new_blog')}}">Add</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-5">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.profile',uname=current_user.username)}}"
                    title="profile">{{current_user.username}}</a>

            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">Sign out</a>
            </li>
            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
            </li>
            {% endif %}
        </ul>

    </div>
</nav>

app/templates/new_blog.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
                {{ wtf.quick_form(blog_form) }}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}

app/templates/new_comment.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{ wtf.quick_form(comment_form) }}
        </div>
        <div class="col md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{% block content %}

<div class="container">
    <div class="row">
        <!--Displaying Username-->
        <div class="col-md-4">
            <h3>{{user.username|capitalize}}</h3>
            <!--Displaying User bio-->
            {% if user.bio %}
            <p>{{user.bio}}</p>

            {%else%}
            <p>{{user.username|capitalize}} has no bio</p>
            {% endif %}

            {% if user == current_user %}
            <a class="btn btn-sm btn-outline-info" href="{{url_for('main.update_profile',uname=user.username)}}">Edit
                profile</a>



            {% endif %}
        </div>
        <!--Displaying pofile photo -->
        <div class="col-md-4">



            {% if user.profile_pic_path %}

            <img class="img-circle" src="{{url_for('static',filename=user.profile_pic_path)}}" alt=""
                class="img-thumbnail" height="200px" width="200px" style="border-radius:50%">

            {%else%}
            <p>No profile picture</p>

            {% endif %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">

            </form>
        </div>
    </div>
</div>

{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}